apiVersion: v1
data:
  JWT_SECRET: 63059c735adba274cde40f2b1c0b955842d531b115bb4df3058d769b173dcc78
  MATCH_TIMEOUT: "30"
  PORT: "8081"
  QUESTION_SERVICE_GRPC_URL: question-service:50051
  REDIS_URL: redis-container:6379
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: matching-service-matching-service-env
  name: matching-service-env
