apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: matching-service
  name: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: matching-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: matching-service
    spec:
      containers:
        - env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: matching-service-env
            - name: MATCH_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  key: MATCH_TIMEOUT
                  name: matching-service-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: matching-service-env
            - name: QUESTION_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  key: QUESTION_SERVICE_GRPC_URL
                  name: matching-service-env
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  key: REDIS_URL
                  name: matching-service-env
          image: matching-service
          name: matching-service
          ports:
            - containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /matching-service
              name: matching-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: matching-service-cm0
          name: matching-service-cm0
