apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: user-service
    spec:
      containers:
        - env:
            - name: DB_CLOUD_URI
              valueFrom:
                configMapKeyRef:
                  key: DB_CLOUD_URI
                  name: user-service-env
            - name: DB_LOCAL_URI
              valueFrom:
                configMapKeyRef:
                  key: DB_LOCAL_URI
                  name: user-service-env
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  key: ENV
                  name: user-service-env
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  key: JWT_SECRET
                  name: user-service-env
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: PORT
                  name: user-service-env
          image: user-service
          name: user-service
          ports:
            - containerPort: 3001
              protocol: TCP
          volumeMounts:
            - mountPath: /user-service
              name: user-service-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: user-service-cm0
          name: user-service-cm0
