name: Run Tests

on:
  push:
    branches:
      - main
      - staging
      - frontend-websocket-test
  pull_request:
    branches:
      - main
      - staging
  workflow_dispatch:

jobs:
  test-firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: emulators:start --only firestore --project demo-test-project
          env:
            GCP_SA_KEY: asdf
